### PR TITLE
Fix verifier evals

### LINKED ISSUE #355: Verifier panics when a fixed column has multiple rotation queries
### Context & versions:

Bug present in `main` and not in `next`

### Steps to reproduce:
```
cargo run --example ethereum_signature --release
```
### Actual behavior:

```
>> Testing Ethereum signature verification
 - Deserialising public key...
 - Deserialising signatures...
 - Setting up vk...
 - Proof generation...
 - Proof verification...

thread 'main' panicked at /Users/queremendi/iohk/midnight/midnight-zk/proofs/src/plonk/verifier.rs:302:25:
insertion index (is 24) should be <= len (is 22)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Expected behavior:

Example expected to run correctly.

### PR DESCRIPTION
**Pull request by iquerejeta**
Fixes #355

### CODE REVIEW

File: proofs/src/plonk/verifier.rs [hunk 1]
```diff
@@ -290,13 +290,18 @@ where
...
-    let mut fixed_evals = read_n(
-        transcript,
-        vk.cs.num_fixed_columns() - vk.cs.num_simple_selectors(),
-    )?;
+    // Read one eval per non-simple-selector fixed query from the transcript,
+    // then fill the "missing" places with 1 (the transcript doesn't contain evals
+    // corresponding to multiplicative, simple selectors).
+    // We count queries (not unique columns) because the same column can appear
+    // multiple times in fixed_queries at different rotation points.
+    let num_non_selector_fixed_queries = vk
```
Comment (miguel-ambrona) [inline proofs/src/plonk/verifier.rs]: `num_fixed_queries_ignoring_simple_selectors`

**Review by miguel-ambrona — DISMISSED** [review]

File: proofs/src/plonk/verifier.rs (hunk 1 above)
Comment (remalue) [inline proofs/src/plonk/verifier.rs]: I suggest to do this:

```
let mut fixed_evals = read_n(
  transcript,
  vk.cs.fixed_queries().len() - vk.cs.num_simple_selectors(),
)?;
```

We have `fixed queries = simple selector queries + non-simple selector queries + non-selector fixed queries`, so this change gives us all fixed queries except those corresp. to simple selectors. This also matches the prover side.

**Review by miguel-ambrona — APPROVED** [review]
